### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by ryanmphill** [ryanmphill/gastro-gnome-next-client#9]
## View a user's profile

- When a user clicks an authors name when viewing a recipe (in the recipe page OR on the recipe feed), they should be navigated to that users profile page.
- When a user clicks "profile" in the navigation dropdown menu, they should be navigated to their own profile page
     - Any users unfollowed when viewing the user's "following" section should be automatically refreshed in the list
     - Any favorited posts 'unfavorited' when viewing the users "favorites" section should be automatically refreshed in the list

## TODO:

- [x] Create nested dynamic routes for `/profile/[id]` with the users posts as the index, and `/profile/[id]/followers`, `/profile/[id]/following`, and `/profile/[id]/favorites` as the other nested routes
- [x] Make the profile accessible through clicking on the user's name on recipe page and recipe feed
- [x] Make the users own profile accessible through the `profile` link on the hamburger menu
- [x] Create a shared layout for the profile page
- [x] Add the content for the shared layout
- [x] Create a client component with UI for switching between nested routes (Profile Display Tab)
- [x] Add the content for the index route
- [x] Add the content for the following route
- [x] Add the content for the followers route
- [x] Add the content for the favorites route
- [x] Ensure state is updated and feed is refreshed when users are followed/unfollowed and posts are favorited/unfavorited
